#!/bin/bash

echo "📋 Quick Setup for Facebook OAuth Testing"
echo "=========================================="
echo ""
echo "The Facebook error happens because the app is in Development Mode."
echo ""
echo "✅ EASIEST FIX:"
echo "1. Go to: https://developers.facebook.com/apps/2328965314198107/roles/roles/"
echo "2. Under 'Roles', add your Facebook account as:"
echo "   - Administrator OR"
echo "   - Developer OR  "
echo "   - Tester"
echo ""
echo "This allows YOU to test the OAuth flow while the app is in development."
echo ""
echo "=========================================="
echo ""
echo "🔗 Alternative: Use Ngrok for HTTPS Tunnel"  
echo "1. Sign up (free): https://dashboard.ngrok.com/signup"
echo "2. Get your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken"
echo "3. Run: ngrok config add-authtoken YOUR_TOKEN"
echo "4. Run: ngrok http 3000"
echo "5. Update Facebook redirect URI with the ngrok HTTPS URL"
echo ""
